controllers:
  resource: ../src/UserInterface/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

app_lucky_number:
  path: /lucky/number
  controller: App\UserInterface\Controller\LuckyController::number
