openapi: 3.0.0
info:
  title: "User API"
  version: "0.1"
servers:
  - url: "http://localhost"
paths:
  /users:
    post:
      tags:
        - User
      operationId: 'App\User\UserInterface\Controller::create'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  description: "User name"
                  type: string
                password:
                  description: "User password"
                  type: string
              type: object
      responses:
        "201":
          description: "User created"
          #content:
          #  application/json:
          #    schema:
          #      $ref: "#/components/schemas/UserResource"
        #default:
        #  description: "An error occured"
        #  content:
        #    application/json:
        #      schema:
        #        properties:
        #          status:
        #            {
        #              description: "The response status",
        #              type: integer,
        #              format: int64,
        #            }
        #          title:
        #            {
        #              description: "The response not detailed message",
        #              type: string,
        #            }
        #        type: object
#components:
#  schemas:
#    UserResource:
#      properties:
#        id:
#          description: 'The user id'
#          type: string
#        name:
#          description: 'The user name'
#          type: string
#      type: object
